export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU';

export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU';

export const CREATE_TASK = 'CREATE_TASK';

export const REMOVE_TASK = 'REMOVE_TASK';

export const CHANGE_CURRENT_TASK = 'CHANGE_CURRENT_TASK';

export const EDIT_TASK = 'EDIT_TASK';

export const CHANGE_CURRENT_CURRENT_EDITING_TASK = 'CHANGE_CURRENT_EDITTING_TASK';

export const ADD_NEW_TASK_ITEM_IN_CURRENT_EDITING_TASK = 'ADD_NEW_ITEM_IN_CURRENT_EDITING_TASK';

export const REMOVE_TASK_ITEM_IN_CURRENT_EDITING_TASK = 'REMOVE_ITEM_IN_CURRENT_EDITING_TASK';

export const SYNC_CURRENT_EDITING_TASK_TO_TASKS = 'SYNC_CURRENT_EDITING_TASK_TO_TASKS';

export const RESET_IS_EDITING_TASK_EDITED = 'RESET_IS_EDITING_TASK_EDITED';

export const COMPLETE_THE_FIRST_UNCHECKED_TASK_ITEM = 'COMPLETE_THE_FIRST_UNCHECKED_TASK_ITEM';

export const COMPLETE_ALL_UNCHECKED_TASK_ITEM = 'COMPLETE_ALL_UNCHECKED_TASK_ITEM';

export const TOGGLE_TASK_ITEM_CHECKED = 'TOGGLE_TASK_ITEM_CHECKED';
