export const SHOW_SIDE_MENU = 'global/SHOW_SIDE_MENU';

export const HIDE_SIDE_MENU = 'global/HIDE_SIDE_MENU';

export const SHOW_ACCOUNT_MANAGER = 'SHOW_ACCOUNT_MANAGER';

export const HIDE_ACCOUNT_MANAGER = 'HIDE_ACCOUNT_MANAGER';

export const ADD_ONE_NOTIFICATION = 'ADD_ONE_NOTIFICATION';

export const REMOVE_THE_TOP_NOTIFICATION = 'REMOVE_THE_TOP_NOTIFICATION';

// export const CHANGE_CURRENT_PATH = 'global/CHANGE_CURRENT_PATH';
