export const SHOW_SIDE_MENU = 'global/SHOW_SIDE_MENU';

export const HIDE_SIDE_MENU = 'global/HIDE_SIDE_MENU';

export const ADD_ONE_NOTIFICATION = 'ADD_ONE_NOTIFICATION';

export const REMOVE_THE_TOP_NOTIFICATION = 'REMOVE_THE_TOP_NOTIFICATION';
