export const SET_PROJECTS = 'SET_PROJECTS';

export const SET_TODO_PROJECT = 'SET_TODO_PROJECT';
export const CLEAR_TODO_PROJECT = 'CLEAR_TODO_PROJECT';

export const SET_EDITING_PROJECT = 'SET_EDITING_PROJECT';
export const CLEAR_EDITING_PROJECT = 'CLEAR_EDITING_PROJECT';

export const ADD_PROJECT = 'ADD_PROJECT';
export const DEL_PROJECT_BY_ID = 'DEL_PROJECT_BY_ID';

export const ADD_TASK_TO_EDITING_PROJECT = 'ADD_TASK_TO_EDITING_PROJECT';
export const DEL_TASK_IN_EDITING_PROJECT = 'DEL_TASK_IN_EDITING_PROJECT';

export const TOGGLE_CHECK_TASK_IN_TODO_PROJECT_BY_ID = 'TOGGLE_CHECK_TASK_IN_TODO_PROJECT_BY_ID';
export const SET_ONE_PROJECT_IS_PINEED_BY_ID = 'SET_ONE_PROJECT_IS_PINEED';
