export const SET_PROJECTS = 'SET_PROJECTS';

// todo project 相关
export const SET_TODO_PROJECT = 'SET_TODO_PROJECT';
export const CLEAR_TODO_PROJECT = 'CLEAR_TODO_PROJECT';
export const SET_IS_FETCHING_TODO_PROJECT = 'SET_IS_FETCHING_TODO_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DEL_PROJECT_BY_ID = 'DEL_PROJECT_BY_ID';
export const TOGGLE_CHECK_TASK_IN_TODO_PROJECT_BY_ID = 'TOGGLE_CHECK_TASK_IN_TODO_PROJECT_BY_ID';

// editing project 相关
export const SET_EDITING_PROJECT = 'SET_EDITING_PROJECT';
export const CLEAR_EDITING_PROJECT = 'CLEAR_EDITING_PROJECT';
export const SET_IS_FETCHING_EDITING_PROJECT = 'SET_IS_FETCHING_EDITING_PROJECT';
export const ADD_TASK_TO_EDITING_PROJECT = 'ADD_TASK_TO_EDITING_PROJECT';
export const DEL_TASK_IN_EDITING_PROJECT = 'DEL_TASK_IN_EDITING_PROJECT';


// 编辑相关
export const SET_ONE_PROJECT_IS_PINEED_BY_ID = 'SET_ONE_PROJECT_IS_PINEED';
export const CHANGE_EDITING_PROJECT_NAME = 'CHANGE_EDITING_PROJECT_NAME';
export const CHANGE_PROJECT_NAME_BY_ID = 'CHANGE_PROJECT_NAME_BY_ID';

// 时间旅行相关
export const SNAPSHOT_EDITINGP_PROJECT = 'SNAPSHOT_EDITINGP_PROJECT';
export const REDO_EDITING_PROJECT = 'REDO_EDITING_PROJECT';
export const UNDO_EDITING_PROJECT = 'UNDO_EDITING_PROJECT';
export const CLEAR_EDITING_HISTORY = 'CLEAR_EDITING_HISTORY';
export const CLEAR_EDITING_PROJECT_FUTURE = 'CLEAR_EDITING_PROJECT_FUTURE';
