/* eslint-disable operator-linebreak */
export const ADD_TASK_TO_TASKS = 'tasks/ADD_TASK_TO_TASKS';

export const REMOVE_TASK_IN_TASKS = 'tasks/REMOVE_TASK_IN_TASKS';

export const CHANGE_CURRENT_TODO_TASK = 'tasks/CHANGE_CURRENT_TODO_TASK';

export const CHANGE_CURRENT_TODO_TASK_BY_ID =
  'tasks/CHANGE_CURRENT_TODO_TASK_BY_ID';

export const ADD_TASK_ID_TO_RECENT_TASK_IDS =
  'tasks/ADD_TASK_ID_TO_RECENT_TASK_IDS';

export const REMOVE_TASK_ID_IN_RECENT_TASK_IDS =
  'tasks/REMOVE_TASK_ID_IN_RECENT_TASK_IDS';

export const ADD_TASK_ID_TO_PINNED_TASK_IDS =
  'tasks/ADD_TASK_ID_TO_PINNED_TASK_IDS';

export const REMOVE_TASK_ID_IN_PINNED_TASK_IDS =
  'tasks/REMOVE_TASK_ID_IN_PINNED_TASK_IDS';

// -- task item

export const CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX =
  'tasks/CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX';

export const CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_TASK_ID =
  'tasks/CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_TASK_ID';

export const TOGGLE_TASK_ITEM_CHECKED = 'tasks/TOGGLE_TASK_ITEM_CHECKED';

// editing task

export const UPDARE_TASK_FROM_EDTING = 'tasks/UPDARE_TASK_FROM_EDTING';

// -- tobe removed
