export const ADD_TASK_TO_TASKS = 'ADD_TASK_TO_TASKS';

export const REMOVE_TASK_IN_TASKS = 'REMOVE_TASK_IN_TASKS';

export const CHANGE_CURRENT_TODO_TASK = 'CHANGE_CURRENT_TODO_TASK';

export const CHANGE_CURRENT_TODO_TASK_BY_ID = 'CHANGE_CURRENT_TODO_TASK_BY_ID';

export const ADD_TASK_ID_TO_RECENT_TASK_IDS = 'ADD_TASK_ID_TO_RECENT_TASK_IDS';

export const REMOVE_TASK_ID_IN_RECENT_TASK_IDS = 'REMOVE_TASK_ID_IN_RECENT_TASK_IDS';

export const ADD_TASK_ID_TO_PINNED_TASK_IDS = 'ADD_TASK_ID_TO_PINNED_TASK_IDS';

export const REMOVE_TASK_ID_IN_PINNED_TASK_IDS = 'REMOVE_TASK_ID_IN_PINNED_TASK_IDS';

// -- task item

export const CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX = 'CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX';

export const TOGGLE_TASK_ITEM_CHECKED = 'TOGGLE_TASK_ITEM_CHECKED';

// -- tobe removed

export const SYNC_CURRENT_EDITING_TASK_TO_TASKS = 'SYNC_CURRENT_EDITING_TASK_TO_TASKS';

// export const REMOVE_TASK_ITEM_IN_CURRENT_EDITING_TASK = 'REMOVE_ITEM_IN_CURRENT_EDITING_TASK';

// export const ADD_NEW_TASK_ITEM_IN_CURRENT_EDITING_TASK = 'ADD_NEW_ITEM_IN_CURRENT_EDITING_TASK';

// export const RESET_IS_EDITING_TASK_EDITED = 'RESET_IS_EDITING_TASK_EDITED';

// export const COMPLETE_THE_FIRST_UNCHECKED_TASK_ITEM = 'COMPLETE_THE_FIRST_UNCHECKED_TASK_ITEM';

// export const COMPLETE_ALL_UNCHECKED_TASK_ITEM = 'COMPLETE_ALL_UNCHECKED_TASK_ITEM';

// -- to be removed

// export const CHANGE_CURRENT_TASK_ID = 'CHANGE_CURRENT_TASK';

// export const EDIT_TASK = 'EDIT_TASK';

// export const CHANGE_CURRENT_CURRENT_EDITING_TASK = 'CHANGE_CURRENT_EDITTING_TASK';
