export const ADD_TASK_TO_TASKS = 'ADD_TASK_TO_TASKS';

export const REMOVE_TASK_IN_TASKS = 'REMOVE_TASK_IN_TASKS';

export const CHANGE_CURRENT_TODO_TASK = 'CHANGE_CURRENT_TODO_TASK';

export const CHANGE_CURRENT_TODO_TASK_BY_ID = 'CHANGE_CURRENT_TODO_TASK_BY_ID';

export const ADD_TASK_ID_TO_RECENT_TASK_IDS = 'ADD_TASK_ID_TO_RECENT_TASK_IDS';

export const REMOVE_TASK_ID_IN_RECENT_TASK_IDS = 'REMOVE_TASK_ID_IN_RECENT_TASK_IDS';

export const ADD_TASK_ID_TO_PINNED_TASK_IDS = 'ADD_TASK_ID_TO_PINNED_TASK_IDS';

export const REMOVE_TASK_ID_IN_PINNED_TASK_IDS = 'REMOVE_TASK_ID_IN_PINNED_TASK_IDS';

// -- task item

export const CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX = 'CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_INDEX';

export const CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_TASK_ID = 'CHECK_TASK_ITEM_IN_TASK_ITEMS_BY_TASK_ID';

export const TOGGLE_TASK_ITEM_CHECKED = 'TOGGLE_TASK_ITEM_CHECKED';

// editing task

export const UPDARE_TASK_FROM_EDTING = 'UPDARE_TASK_FROM_EDTING';

// -- tobe removed
