// export const EFFECT_LOGIN = 'EFFECT_LOGIN';

// export const EFFECT_REGISTER = 'EFFECT_REGISTER';

export const EFFECT_CREATE_TASK = 'EFFECT_CREATE_TASK';

export const EFFECT_UPDATE_TASK = 'EFFECT_UPDATE_TASK';
